###############################################################################
# scripts/fm/lec_rtl_vs_gate.tcl -- Formality RTL-vs-gate equivalence check
#
# Proves the final gate-level netlist (outputs/<run>/<TOP>.v, post-fill,
# post-route, post change_names -- exactly what 06_finish.tcl exports to
# GDS) is logically equivalent to the original RTL (croc.flist).
#
# SVF_FILE (optional): path to the .svf FC's compile_fusion wrote during
# 03_synthesis.tcl (set_verification_checkpoints, added 2026-08-15
# specifically because a plain/non-SVF run got stuck at ~99% "Unverified"
# compare points -- see the git history of this file and
# scripts/03_synthesis.tcl for the full root-cause trail). If set, it is
# passed to Formality via set_svf BEFORE any design is read (required --
# `man set_svf`: "You can use the set_svf command only before reading a
# design"), letting Formality correlate compare points using FC's own
# transformation record instead of matching from scratch.
#
# STATUS (2026-08-15): tried against a real checkpoint SVF (19.7MB,
# generated by 03_synthesis.tcl with set_verification_checkpoints on a full
# re-synth) and it did NOT improve on the plain run -- Formality logged
# "SVF-DESIGN: Files with missing guide_file_info: 82" and "Checkpoint (SVF
# Operation 57) ... Status: Checkpoint Verification FAILED, guide_checkpoint
# 57 rejected", then fell back to essentially the same from-scratch matching
# (final counts identical to the plain run bar Formality's own bookkeeping).
# This looks like an elaboration-context mismatch: the checkpoint records
# FC's own internal analyze/elaborate state from work/ (01_read_rtl.tcl:
# `analyze -format sverilog -vcs "-F ../croc.flist"` with manually-added
# +incdir+ search_path entries), which this script's plain `read_sverilog -r
# -vcs "-F $FLIST"` from the repo root does not exactly reproduce. Running
# from work/ with FLIST=../croc.flist to match FC's cwd was tried and made
# things WORSE (file-not-found errors -- FC's extra manual search_path
# handling in 01_read_rtl.tcl is load-bearing and wasn't replicated here).
# Left as a documented dead end for now rather than chased further; a more
# complete fix would likely mean reading FC's actual postcompile checkpoint
# database directly (`read_db -svf_postcompile_db_list`, seen in `read_db
# -help` but not yet investigated) instead of re-elaborating RTL and hoping
# it lines up with the checkpoint. Leave SVF_FILE empty for a plain run (the
# validated, working mode -- see STATUS below) -- e.g. to re-check an older
# build that predates
# set_verification_checkpoints).
#
# Library setup mirrors scripts/pt/sta_corner.tcl (same 3 .db files: standard
# cell, IO pad, SRAM macro -- PVT corner is irrelevant for logic equivalence,
# "typical" was picked arbitrarily for a single consistent set), but here
# they're read as TECHNOLOGY LIBRARIES into BOTH containers, not just the
# implementation side. This is required, not just tidy: croc's RTL directly
# instantiates a handful of real standard cells by name (tc_clk.sv's
# tc_clk_mux2/tc_clk_inverter wrappers use gf180mcu_fd_sc_mcu7t5v0__mux2_1/
# __clkinv_1 directly -- a common ASIC-RTL idiom for clock-tree-safe
# primitives) and the real SRAM macro (gf180mcu_fd_ip_sram__sram512x8m8wm1,
# via tc_sram.sv's TARGET_GF180 branch) -- without technology-library
# resolution on the REFERENCE side too, `set_top` fails outright with
# "Unresolved references detected during link" (FE-LINK-2/FM-234, confirmed
# 2026-08-15).
#
# Why the SRAM isn't read as RTL and black-boxed instead: its own vendor
# simulation model (rtl/tech_cells/gf180/gf180mcu_fd_ip_sram__sram512x8m8wm1.v)
# uses a Verilog construct Formality's formal-RTL parser rejects outright
# (FMR_VLOG-206, "Condition in the if_elseif statement does not match those
# in the event control list" -- a full-timing-check simulation idiom, not a
# synthesizable/formalizable one). Resolving it via the liberty .db instead
# sidesteps that broken source entirely: Formality treats a RAM-type library
# cell with no per-pin function equation as an opaque primitive by
# construction, so it comes out black-boxed on both sides for free, with no
# explicit set_black_box call needed (confirmed 2026-08-15: no "cannot link"
# warnings for it once the .db was loaded before read_sverilog/read_verilog).
###############################################################################

foreach v {TOP VLOG FLIST SC_DB IO_DB SRAM_DB REPORT_DIR} {
  if { ![info exists $v] } {
    puts "ERROR: required variable '$v' not set -- see header comment in [info script]."
    exit 1
  }
}
if { ![info exists SVF_FILE] } { set SVF_FILE "" }

file mkdir $REPORT_DIR

if { $SVF_FILE != "" } {
  puts "INFO: Using SVF guidance: $SVF_FILE"
  set_svf $SVF_FILE
}

# croc_soc is a single power-domain design (power_grid.tcl ties every macro
# to one design-wide VDD/VSS net, no UPF anywhere in this flow), so PG
# connectivity isn't part of what this LEC run is scoped to check -- that's
# LVS's job (already covered by make lvs/lvs-icv). Formality's default
# strict PG-netlist handling is aimed at UPF-based multivoltage designs;
# without these two relaxations, set_top fails outright on both sides
# (confirmed 2026-08-15: FM-565 "Port VDD ... type supply1 ... not
# appropriate for equivalence checking" and FM-619 "Missing power and ground
# pin connections ... hdlin_allow_partial_pg_netlist set to false").
set_app_var hdlin_error_on_supply_type_port false
set_app_var hdlin_allow_partial_pg_netlist true

# First plain (non-SVF) run (2026-08-15) matched/verified only 30 of ~4100
# compare points (10 pass, 20 fail, rest unverified). analyze_points -failing
# traced essentially all of it to two root causes, not a real design bug:
#   1. r:/WORK/croc_soc/i_croc/all_sbr_obi_rsp[4].rvalid is genuinely
#      undriven in the RTL (an unused/reserved OBI subordinate response
#      slot) -- Formality's default BINARY:X handling treats an undriven
#      reference signal as a free variable, which then makes every
#      downstream compare point unmatchable/failing by construction.
#   2. i:/WORK/croc_soc/i_rstgen_i_rstgen_bypass_synch_regs_q_reg_3_ was the
#      single largest X-source, propagating to all 20 failing points.
# verification_set_undriven_signals=SYNTHESIS, set_constant, and
# create_cutpoint_blackbox/set_constant on testmode_i (below) were all tried
# against the plain run; none moved the numbers (confirmed 2026-08-15,
# byte-identical reruns each time) -- consistent with FC's synthesis having
# transformed the design too heavily for Formality's from-scratch structural
# matching to follow without SVF guidance. Left in place under SVF too
# (harmless either way -- they only affect VALUE resolution, not matching),
# but re-run analyze_points after enabling SVF_FILE before assuming these
# are still doing anything useful; SVF guidance may make them redundant.
set verification_set_undriven_signals SYNTHESIS

###############################################################################
# 1. Reference (RTL) side
###############################################################################
read_db -r -technology_library $SC_DB
read_db -r -technology_library $IO_DB
read_db -r -technology_library $SRAM_DB

read_sverilog -r -vcs "-F $FLIST"

# Standard, expected RTL-interpretation ambiguities for a design this size
# (unique/parallel_case overlap, array-index-may-exceed-bound) -- see this
# file's header comment; acknowledging them is required before set_top will
# proceed at all, not a correctness shortcut taken here.
set_mismatch_message_filter -warn FMR_ELAB-116
set_mismatch_message_filter -warn FMR_ELAB-147

set_top r:/WORK/$TOP

set XBAR_MGR4_RVALID [get_nets -exact -quiet {r:/WORK/croc_soc/i_croc/i_main_xbar/mgr_ports_rsp_i[4]\[rvalid]}]
if { [sizeof_collection $XBAR_MGR4_RVALID] > 0 } {
  create_cutpoint_blackbox cut_unused_xbar_mgr4_rvalid $XBAR_MGR4_RVALID
} else {
  puts "INFO: mgr_ports_rsp_i\[4\].rvalid not found (name changed, or SVF resolved it already) -- skipping cutpoint."
}

# testmode_i left unconstrained is what the pre-SVF investigation traced the
# rstgen X-source to (rtl/common_cells/rstgen_bypass.sv: test_mode_i selects
# a tc_clk_mux2 between the normal reset synchronizer chain and a test-mode
# bypass path). STA already assumes it is tied 0 in functional mode
# (scripts/common/mode_func.tcl section 5). Pinning it here mirrors an
# assumption this project already signs off against, not a new one invented
# for LEC.
set TESTMODE_R [get_ports -quiet r:/WORK/croc_soc/testmode_i]
if { [sizeof_collection $TESTMODE_R] > 0 } { set_constant -type port $TESTMODE_R 0 }

###############################################################################
# 2. Implementation (gate-level) side
###############################################################################
read_db -i -technology_library $SC_DB
read_db -i -technology_library $IO_DB
read_db -i -technology_library $SRAM_DB

read_verilog -i -netlist $VLOG

set_top i:/WORK/$TOP

set TESTMODE_I [get_ports -quiet i:/WORK/croc_soc/testmode_i]
if { [sizeof_collection $TESTMODE_I] > 0 } { set_constant -type port $TESTMODE_I 0 }

###############################################################################
# 3. Match + verify
###############################################################################
match

redirect -file ${REPORT_DIR}/report_unmatched_points.rpt { report_unmatched_points }
redirect -file ${REPORT_DIR}/report_black_boxes.rpt { report_black_boxes }

verify

redirect -file ${REPORT_DIR}/report_verification_status.rpt { report_status }
redirect -file ${REPORT_DIR}/report_failing_points.rpt { report_failing_points }
redirect -file ${REPORT_DIR}/report_passing_points.rpt { report_passing_points }
redirect -file ${REPORT_DIR}/analyze_points_failing.rpt { analyze_points -failing -effort high }

puts "INFO: Formality RTL-vs-gate LEC complete. Reports in $REPORT_DIR"
