// Copyright (c) 2026.
// Licensed under the Apache License, Version 2.0.
//
// MNIST 196->32->10 int8 MLP inference on Croc (single-core Ibex).
// Mirrors the helloworld.c structure: uart_init -> compute -> printf -> flush.
//
// NOTE: print.c's printf only implements "%x", so the digit is printed in hex
//       (0-9 print as a single hex char, which is exactly what we need).

#include "uart.h"
#include "print.h"
#include "config.h"

#include "nn_linear.h"
#include "mnist_model.h"   // generated by train_export_mnist.py (placeholder until then)

int main(void)
{
    uart_init();

    static uint8_t hidden[DIM_H];
    static int32_t logits[DIM_OUT];

    // Layer 1: 196 uint8 -> 32 acc -> requant + ReLU -> 32 uint8
    nn_linear_u8_relu(mnist_test_image, mnist_W1, mnist_b1, hidden,
                      DIM_IN, DIM_H, mnist_out_mult1, mnist_out_shift1);

    // Layer 2: 32 uint8 -> 10 int32 logits (no requant; argmax)
    nn_linear_out32(hidden, mnist_W2, mnist_b2, logits, DIM_H, DIM_OUT);

    int pred = nn_argmax_i32(logits, DIM_OUT);

    printf("MNIST predicted digit: %x\n", (unsigned)pred);
    printf("expected: %x\n", (unsigned)mnist_test_label);

    uart_write_flush();
    return 0;
}
