// Copyright (c) 2026.
// Licensed under the Apache License, Version 2.0.
//
// "Hey Croc" keyword-spotting inference on Croc (single-core Ibex).
// DNN classifier (250 -> 32 -> 32 -> 12) over precomputed MFCC features.
// Reuses the SAME kernels as the MNIST example (nn_linear.c) -- no new code.
//
// NOTE: print.c's printf only implements "%x", but literal characters in the
//       format string are emitted as-is, so we can still print class names.

#include "uart.h"
#include "print.h"
#include "config.h"

#include "nn_linear.h"
#include "kws_model.h"   // generated by train_export_kws.py (placeholder until then)

// Class order MUST match train_export_kws.py LABELS and kws_model.h.
static void print_label(int c)
{
    switch (c) {
        case 0:  printf("silence\n"); break;
        case 1:  printf("unknown\n"); break;
        case 2:  printf("yes\n");     break;
        case 3:  printf("no\n");      break;
        case 4:  printf("up\n");      break;
        case 5:  printf("down\n");    break;
        case 6:  printf("left\n");    break;
        case 7:  printf("right\n");   break;
        case 8:  printf("on\n");      break;
        case 9:  printf("off\n");     break;
        case 10: printf("stop\n");    break;
        case 11: printf("go\n");      break;
        default: printf("?\n");       break;
    }
}

int main(void)
{
    uart_init();

    static uint8_t h1[H1];
    static uint8_t h2[H2];
    static int32_t logits[NUM_CLASS];

    // Layer 1: MFCC (uint8, asymmetric; zero-point folded into kws_b1) -> 32 ReLU
    nn_linear_u8_relu(kws_test_feat, kws_W1, kws_b1, h1,
                      NUM_FEAT, H1, kws_out_mult1, kws_out_shift1);
    // Layer 2: 32 -> 32 ReLU
    nn_linear_u8_relu(h1, kws_W2, kws_b2, h2,
                      H1, H2, kws_out_mult2, kws_out_shift2);
    // Layer 3: 32 -> 12 logits (no requant; argmax)
    nn_linear_out32(h2, kws_W3, kws_b3, logits, H2, NUM_CLASS);

    int pred = nn_argmax_i32(logits, NUM_CLASS);

    printf("KWS predicted class: %x\n", (unsigned)pred);
    print_label(pred);
    printf("expected: %x\n", (unsigned)kws_test_label);

    uart_write_flush();
    return 0;
}
